### ISSUE TITLE
WasteSmart assessment

### ISSUE THREAD

**Issue by AnnaHavard** [CIWM/Client-Hub#9]
![client hub issue - r mcewan](https://cloud.githubusercontent.com/assets/13269824/9056504/3c1a019c-3a8b-11e5-8183-4b604903fb6b.jpg)

From: Anna Havard 
Sent: 04 August 2015 09:25
To: Nick Garrod
Subject: FW: CIWM Learning Hub - WasteSmart Programme

Hi Nick

Please can you look into this issue asap, it seems the system isn’t recognising second attempts and also isn’t limiting people to two attempts. I’ll also raise it on git hub.

Thanks, Anna

From: McEwen, Richard [mailto:Richard.Mcewen@sodexo.com] 
Sent: 04 August 2015 08:35
To: Kent Love <Kent.love@ciwm.co.uk>
Subject: FW: CIWM Learning Hub - WasteSmart Programme
 
Dear Kent,
please see below as i require some assistance
many thank
 
R. McEwen 
Richard McEwen 
Admin Officer, Defence 
Sodexo 
QM Central Services 
Building D07, Merville Barracks 
Colchester, Essex, CO2 7UT, UK 
+44 1206 816442 
Richard.Mcewen@sodexo.com 
Sodexo.World Leader in Quality of Life Services-www.sodexo.com 
Join in the fight against hunger: www.stophunger.org.uk 
 

________________________________________
From: McEwen, Richard 
Sent: 04 August 2015 08:15
To: 'Rebecca Penberthy'
Cc: Atkins-morris, Claire
Subject: RE: CIWM Learning Hub - WasteSmart Programme
Dear Rebecca,
I Have Completed the Course, I failed the first assesment and got 62%, I then passed the second attempt with a score of 82% and nothing was registered so i tryed again and got 72% as per attachement. your help in this matter is much appreciated.
 
R. McEwen 
Richard McEwen 
Admin Officer, Defence 
Sodexo 
QM Central Services 
Building D07, Merville Barracks 
Colchester, Essex, CO2 7UT, UK 
+44 1206 816442 
Richard.Mcewen@sodexo.com

**Comment by nick69g** [comment]
I've tested this and it appears to work fine and as expected.

Once the learner has had their first attempt they must choose to start a new attempt (as shown below) otherwise they will in theory comple the first attempt again and a new score will not be achieved.

Once two attempts have been reached they get locked out (also shown below).
[cid:5E3DAB43-6A18-4AEB-9936-C50C0358CB7D]
[cid:0E0A30E1-460A-4F67-97FF-B66E63E9D843]

**Comment by AnnaHavard** [comment]
Thanks for the quick response, unfortunately the images aren't showing in your response so it's hard to work out what's happening. Can you resend the images please.

**Comment by AnnaHavard** [comment]
![maximum attempts picture](https://cloud.githubusercontent.com/assets/13269824/9058033/0dc2a94c-3a96-11e5-817a-9c721f1e67a0.jpg)
![new attempt picture](https://cloud.githubusercontent.com/assets/13269824/9058034/0dc3da42-3a96-11e5-81cc-a372135415b6.jpg)

**Comment by AnnaHavard** [comment]
Images uploaded above.

Regarding Richard's description; he appears to have done the assessment three times and got a higher score than is showing on the client hub reports. Please can you confirm how he's done this given the test you've described above? 

If he's managed to resit his first attempt, rather than starting a new attempt how did he do this and how do we stop it happening in the future?

If he has resat his first attempt why isn't the client hub showing his latest score of 72% as shown on his attachment? The client hub shows one attempt with a score of 61%.

**Comment by nick69g** [comment]
Unfortunately this is one of the "quirks" of Moodle which cannot be changed if you want to limit the number of attempts. Maybe we need to add some learner instructions...

This is how it works:

Attempt 1

Learner scores 50%.

They have another attempt without "selecting a new attempt" - this means they are repeating Attempt 1 (almost having a "practice/review" before making another proper attempt). This time they score 60%, but because it is the same attempt, the higher score is not saved.

Attempt 2

They select "new attempt" and will be in attempt number 2. If they score less than their first attempt then the first attempt score will be maintained, if they score higher, the higher attempt score is recorded.

After two "proper attempts" the system locks them out.

**Comment by AnnaHavard** [comment]
On the ciwm knowledge hub you don't have the option to tell it you want to start a new attempt, it automatically does this for you. Can we replicate this on the client hub?

I know that a few people at Sodexo have done the assessment more than once, am I right in thinking their second attempts will not be recorded anywhere if they didn't tick the box? All Sodexo learners on the hub report are showing as only having made one attempt.

**Comment by nick69g** [comment]
OK I'll have a look at the settings. Only one attempt will be shown if they did not select a new attempt, regardless of whether they have done it 2-3 times. If they have a higher score, we can always override that stored in Moodle.

**Comment by AnnaHavard** [comment]
Will they need to have their own record of their highest score or will it be somewhere in Moodle?

**Comment by nick69g** [comment]
It won't be in Moodle as it has not been stored anywhere.

On 4 Aug 2015, at 11:28, AnnaHavard <notifications@github.com<mailto:notifications@github.com>> wrote:


Will they need to have their own record of their highest score or will it be somewhere in Moodle?

-

**Comment by AnnaHavard** [comment]
OK, please can you rectify Richard McEwan's score based on the screenshot he's sent to us (at the top of this string).

I'll go back to Sodexo with their remaining delegates who are either showing as not attempted or failed and see if anyone else comes back with the same issue. I'm sure there is another delegate who said they've resat the assessment so I'm expecting at least one other person to come back. 

Please can you let me know the timescales for reviewing the settings to make sure it's not possible to resit without it recording a score and an attempt. Thanks

**Comment by AnnaHavard** [comment]
Can we record his score as 82% please as that is the highest score he's reported to us.

**Comment by nick69g** [comment]
Richard's score updated to 82%.
New attempt settings have been updated so that the learner has two attempts without having to select to start a new attempt.

**Comment by AnnaHavard** [comment]
Richard's score on the reports system is still showing as 61%. I have refreshed the report and logged out and back in.

**Comment by nick69g** [comment]
This was down to how the Moodle settings had been configured.

Originally they would have their first attempt and would achieve a score. Their second attempt would in theory be a re-run of their first attempt without recording a new score if they had not selected to "start a new attempt". Starting a new attempt is the only way to gain a new and updated score and exhaust the two attempts available; otherwise teh first attempt can be repeated countless times.

The Moodle settings have now been updated so that a new attempt is automatically forced each time the learner undertake the assessment to a maximum of two attempts.
